# Generated by Django 3.2.1 on 2021-05-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifytoken',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
